security:


    #encoders:
      #Symfony\Component\Security\Core\User\User: plaintext

    providers:
         my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: "dc=brown,dc=gob,dc=ar"
                search_dn: "cn=administrador,ou=Administradores,ou=Usuarios,dc=ar,dc=gob,dc=brown"
                search_password: Network.02
                default_roles: ROLE_USER
                uid_key: uid

    firewalls:
          main:
             http_basic_ldap:

                service: Symfony\Component\Ldap\Ldap
                dn_string: 'uid={username},dc=brown,dc=gob,dc=ar'



    access_control:
         - { path: ^/, roles: ROLE_ADMIN }
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/profile, roles: ROLE_USER }
